version: 2

sources:
  - name: f1_dataset
    database: f1_data_pipeline
    schema: full_data
    tables:
      - name: circuits
      - name: constructors
      - name: constructor_standings
      - name: constructor_results
      - name: drivers
      - name: driver_standings
      - name: lap_times
      - name: pit_stops
      - name: qualifying
      - name: races
      - name: results
      - name: seasons
      - name: status
      - name: position_descriptions
      - name: sprint_results