my_own_101:
  outputs:
      dbt_run_local:
        type: "postgres"
        threads: 8
        host: "localhost"
        port: 5436
        user: "postgres"
        pass: "postgres"
        dbname: "f1_data_pipeline"
        schema: "output_own_101"

  target: dbt_run_local


view_selection_tool:
  outputs:
    default:
      type: postgres
      threads: 8
      host: "localhost"
      port: 5436
      user: "postgres"
      password: "postgres"
      dbname: "f1_data_pipeline"
      schema: "output_own_101_view_selection_tool"