version: 2

sources:
  - name: transfermarkt
    database: transfermarkt
    schema: synthetic_data
    tables:
      - name: game_lineups
      - name: games
      - name: players
      - name: market_value_development
      - name: game_events